config/routes.rb
Rails.application.routes.draw do
  resources :calculations

  root to: "calculations#new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/calculation.rb
class Calculation < ApplicationRecord
  validates :annual_income, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :capital_gains, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :deduction, presence: true, numericality: { greater_than_or_equal_to: 0, allow_blank: true }
  validates :dependent_children, presence: true, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 30 }
  validates :monthly_insurance_premium, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :filing_type, presence: true
  validates :annual_out_of_pocket_costs, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :annual_dental_costs, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :annual_vision_costs, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :annual_hearing_costs, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :annual_drug_costs, presence: true, numericality: { greater_than_or_equal_to: 0 }

  enum filing_type: { single: 0, married_joint: 1, married_single: 2, head_of_household: 3 }

  before_save :fix_deduction
  before_create :create_edit_token

  def fix_deduction
    self.deduction = 0 unless deduction
  end

  def create_edit_token
    self.edit_token = SecureRandom.base58(32)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/calculations_controller.rb
class CalculationsController < ApplicationController
  before_action :set_calculation, only: [:show, :edit, :update, :destroy]
  before_action :check_token, only: [:edit]
  before_action :check_referer, only: [:update]
  before_action :prevent, only: [:index, :delete]

  # GET /calculations
  # GET /calculations.json
  def index
    @calculations = Calculation.all
  end

  # GET /calculations/1
  # GET /calculations/1.json
  def show
    cs = CalculationService.new(@calculation.annual_income,
                                @calculation.capital_gains,
                                @calculation.deduction,
                                @calculation.dependent_children)

    filing_type = @calculation.filing_type.to_sym

    @new_total_taxes = cs.new_total_taxes(filing_type)
    @old_total_taxes = cs.old_total_taxes(filing_type)
    @tax_difference = @old_total_taxes - @new_total_taxes

    @old_expenses = (12 * @calculation.monthly_insurance_premium) + @calculation.annual_out_of_pocket_costs +
                 @calculation.annual_dental_costs + @calculation.annual_vision_costs +
                 @calculation.annual_hearing_costs + @calculation.annual_drug_costs
    @new_expenses = [@calculation.annual_drug_costs || 0, 200].min
    @expenses_difference = @old_expenses - @new_expenses

    @old_total = @old_total_taxes + @old_expenses
    @new_total = @new_total_taxes + @new_expenses
    @total_difference = @old_total - @new_total
  end

  # GET /calculations/new
  def new
    @calculation = Calculation.new
  end

  # GET /calculations/1/edit
  def edit
  end

  # POST /calculations
  # POST /calculations.json
  def create
    @calculation = Calculation.new(calculation_params)

    respond_to do |format|
      if @calculation.save
        format.html { redirect_to calculation_path(@calculation, token: @calculation.edit_token) }
        format.json { render :show, status: :created, location: @calculation }
      else
        format.html { render :new }
        format.json { render json: @calculation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /calculations/1
  # PATCH/PUT /calculations/1.json
  def update
    respond_to do |format|
      if @calculation.update(calculation_params)
        format.html { redirect_to calculation_path(@calculation, token: @calculation.edit_token) }
        format.json { render :show, status: :ok, location: @calculation }
      else
        format.html { render :edit }
        format.json { render json: @calculation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /calculations/1
  # DELETE /calculations/1.json
  def destroy
    @calculation.destroy
    respond_to do |format|
      format.html { redirect_to calculations_url, notice: 'Calculation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_calculation
      @calculation = Calculation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def calculation_params
      pp = params.require(:calculation).permit(:annual_income, :capital_gains, :deduction, :dependent_children,
        :monthly_insurance_premium, :filing_type, :annual_out_of_pocket_costs,
        :annual_dental_costs, :annual_vision_costs, :annual_hearing_costs, :annual_drug_costs)
      pp[:filing_type] = params[:calculation][:filing_type].to_i if params[:calculation] && params[:calculation][:filing_type]
      pp
    end

    def prevent
      redirect_back(fallback_location: root_path, alert: "You're not allowed to take that action")
    end

    def check_token
      unless params[:token] == @calculation.edit_token
        redirect_back(fallback_location: root_path, alert: "You're not allowed to take that action")
      end
    end

    def check_referer
      unless request.referer.last(32) == @calculation.edit_token
        redirect_back(fallback_location: root_path, alert: "You're not allowed to take that action")
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def field_has_error?(model, field)
    model&.errors&.keys&.include?(field) ? 'field-has-errors' : ''
  end
end

app/helpers/calculations_helper.rb
module CalculationsHelper
end

app/views/calculations/_form.html.slim
= form_for @calculation do |f|
  - if @calculation.errors.any?
      ul.mt-3
        - @calculation.errors.full_messages.each do |message|
          .alert.alert-danger = message

  .row.mt-3
    .col-lg-6.col-sm-12
      = f.label :filing_type, "Your tax filing status:", class: "close-label #{field_has_error?(@calculation, :filing_type)}"
  .row.mb-3
    .col-6
      = f.radio_button :filing_type, Calculation.filing_types[:single], checked: @calculation.filing_type == "single"
      = f.label :filing_type, "Single", value: Calculation.filing_types[:single], class: 'radio-label'
    .col-6
      = f.radio_button :filing_type, Calculation.filing_types[:married_joint], checked: @calculation.filing_type == "married_joint"
      = f.label :filing_type, "Married (joint)", value: Calculation.filing_types[:married_joint], class: 'radio-label'
    .col-6
      = f.radio_button :filing_type, Calculation.filing_types[:married_single], checked: @calculation.filing_type == "married_single"
      = f.label :filing_type, "Married (single)", value: Calculation.filing_types[:married_single], class: 'radio-label'
    .col-6
      = f.radio_button :filing_type, Calculation.filing_types[:head_of_household], checked: @calculation.filing_type == "head_of_household"
      = f.label :filing_type, "Head of household", value: Calculation.filing_types[:head_of_household], class: 'radio-label'
  .row.mb-3
    .col-lg-6.col-sm-12
      .form-group
        = f.label :annual_income, "Your annual income:", class: "close-label #{field_has_error?(@calculation, :annual_income)}"
        = f.text_field :annual_income, class: 'form-control with-dollar-sign with-dollar-sign', pattern: '\d*', onchange: "try{setCustomValidity('')}catch(e){}", oninvalid: "setCustomValidity('Please use only numbers (no decimals, commas, or negatives)')", autocomplete: "off"
        span.form-control-dollar-sign $
    .col-lg-6.col-sm-12
      .form-group
        = f.label :capital_gains, "Capital gains:", class: "close-label #{field_has_error?(@calculation, :capital_gains)}"
        = f.text_field :capital_gains, class: 'form-control with-dollar-sign', title: "This means income from stocks, bonds, real estate, investments, etc.", data: { toggle: "tooltip", placement: "top" }, pattern: '\d*', onchange: "try{setCustomValidity('')}catch(e){}", oninvalid: "setCustomValidity('Please use only numbers (no decimals, commas, or negatives)')", autocomplete: "off"
        span.form-control-dollar-sign $

  .row.mb-4
    .col-lg-6.col-sm-12
      .form-group
        = f.label :deduction, "Total deductions:", class: "close-label #{field_has_error?(@calculation, :deduction)}"
        = f.text_field :deduction, class: 'form-control with-dollar-sign', title: "Not sure? Enter 0 and we'll apply the standard deduction for your filing status", data: { toggle: "tooltip", placement: "top" }, pattern: '\d*', onchange: "try{setCustomValidity('')}catch(e){}", oninvalid: "setCustomValidity('Please use only numbers (no decimals, commas, or negatives)')", autocomplete: "off"
        span.form-control-dollar-sign $
    .col-lg-6.col-sm-12
      .form-group
        = f.label :dependent_children, "Number of dependent children you have:", class: "close-label #{field_has_error?(@calculation, :dependent_children)}"
        = f.text_field :dependent_children, class: 'form-control', pattern: '\d*', onchange: "try{setCustomValidity('')}catch(e){}", oninvalid: "setCustomValidity('Please use only numbers (no decimals, commas, or negatives)')", autocomplete: "off"

  .row.mb-3
    .col-lg-6.col-sm-12
      = f.label :monthly_insurance_premium, "Monthly insurance premium:", class: "close-label #{field_has_error?(@calculation, :monthly_insurance_premium)}"
      = f.text_field :monthly_insurance_premium, class: 'form-control with-dollar-sign', id: 'monthly-insurance-premium-input', title: "This is the amount you pay monthly to your insurance company no matter what (even if you receive no medical care)", data: { toggle: "tooltip", placement: "top" }, pattern: '\d*', onchange: "try{setCustomValidity('')}catch(e){}", oninvalid: "setCustomValidity('Please use only numbers (no decimals, commas, or negatives)')", autocomplete: "off"
      span.form-control-dollar-sign $
    .col-lg-6.col-sm-12 style="display: flex"
      .hint-text style="align-self: flex-end" Not sure? Try the <span class="link-like trigger-check" id='use-national-average-premium'>national average</span> or the <span class="link-like trigger-check" id='use-national-90th-percentile-premium'>national 90th percentile</span> for an individual

  .row.mb-3
    .col-lg-6.col-sm-12
      = f.label :annual_out_of_pocket_costs, "Yearly doctor or hospital costs:", class: "close-label #{field_has_error?(@calculation, :annual_out_of_pocket_costs)}"
      = f.text_field :annual_out_of_pocket_costs, class: 'form-control with-dollar-sign', id: 'annual-out-of-pocket-costs-input', title: "This is the amount you paid directly to doctors or hospitals last year", data: { toggle: "tooltip", placement: "top" }, pattern: '\d*', onchange: "try{setCustomValidity('')}catch(e){}", oninvalid: "setCustomValidity('Please use only numbers (no decimals, commas, or negatives)')", autocomplete: "off"
      span.form-control-dollar-sign $
    .col-lg-6.col-sm-12 style="display: flex"
      .hint-text style="align-self: flex-end" Not sure? Try the <span class="link-like trigger-check" id='use-national-average-oop'>national average</span> or the <span class="link-like trigger-check" id='use-national-90th-percentile-oop'>national 90th percentile</span> for an individual

  .row.mb-3
    .col-lg-6.col-sm-12
      = f.label :annual_dental_costs, "Yearly dental care costs:", class: "close-label #{field_has_error?(@calculation, :annual_dental_costs)}"
      = f.text_field :annual_dental_costs, class: 'form-control with-dollar-sign', id: 'annual-dental-costs-input', title: "This is the total you spent on dental insurance and/or care last year", data: { toggle: "tooltip", placement: "top" }, pattern: '\d*', onchange: "try{setCustomValidity('')}catch(e){}", oninvalid: "setCustomValidity('Please use only numbers (no decimals, commas, or negatives)')", autocomplete: "off"
      span.form-control-dollar-sign $
    .col-lg-6.col-sm-12 style="display: flex"
      .hint-text style="align-self: flex-end" Not sure? Try the <span class="link-like trigger-check" id='use-national-average-dental'>national average</span> for an individual

  .row.mb-3
    .col-lg-6.col-sm-12
      = f.label :annual_vision_costs, "Yearly vision care costs:", class: "close-label #{field_has_error?(@calculation, :annual_vision_costs)}"
      = f.text_field :annual_vision_costs, class: 'form-control with-dollar-sign', id: 'annual-vision-costs-input', title: "This is the total you spent on vision insurance and/or care last year", data: { toggle: "tooltip", placement: "top" }, pattern: '\d*', onchange: "try{setCustomValidity('')}catch(e){}", oninvalid: "setCustomValidity('Please use only numbers (no decimals, commas, or negatives)')", autocomplete: "off"
      span.form-control-dollar-sign $
    .col-lg-6.col-sm-12 style="display: flex"
      .hint-text style="align-self: flex-end" Not sure? Try the <span class="link-like trigger-check" id='use-national-average-vision'>national average</span> for an individual

  .row.mb-3
    .col-lg-6.col-sm-12
      = f.label :annual_hearing_costs, "Yearly hearing aid costs:", class: "close-label #{field_has_error?(@calculation, :annual_hearing_costs)}"
      = f.text_field :annual_hearing_costs, class: 'form-control with-dollar-sign', id: 'annual-hearing-costs-input', title: "If you bought hearing aids last year, put the total you spent here", data: { toggle: "tooltip", placement: "top" }, pattern: '\d*', onchange: "try{setCustomValidity('')}catch(e){}", oninvalid: "setCustomValidity('Please use only numbers (no decimals, commas, or negatives)')", autocomplete: "off"
      span.form-control-dollar-sign $
    .col-lg-6.col-sm-12 style="display: flex"
      .hint-text style="align-self: flex-end" Not sure? Try the <span class="link-like trigger-check" id='use-national-average-hearing'>national average</span> for a pair

  .row.mb-3
    .col-lg-6.col-sm-12
      = f.label :annual_drug_costs, "Yearly prescription drug costs:", class: "close-label #{field_has_error?(@calculation, :annual_drug_costs)}"
      = f.text_field :annual_drug_costs, class: 'form-control with-dollar-sign', id: 'annual-drug-costs-input', title: "This is the amount you paid for any prescription drugs last year", data: { toggle: "tooltip", placement: "top" }, pattern: '\d*', onchange: "try{setCustomValidity('')}catch(e){}", oninvalid: "setCustomValidity('Please use only numbers (no decimals, commas, or negatives)')", autocomplete: "off"
      span.form-control-dollar-sign $
    .col-lg-6.col-sm-12 style="display: flex"
      .hint-text style="align-self: flex-end" Not sure? Try the <span class="link-like trigger-check" id='use-national-average-drug'>national average</span> for an individual
  #disabled-button
    span title="All fields must be completed before submitting" data-toggle="tooltip" data-placement="right" style="display: inline-block; cursor: non-allowed"
      .actions = f.submit "Calculate", class: "btn btn-primary", id: "submit-calculation", disabled: "disabled", style: "pointer-events: none"
  #enabled-button.hidden
    .actions = f.submit "Calculate", class: "btn btn-primary", id: "submit-calculation"

br
br

javascript:
  document.addEventListener("turbolinks:load", function() {
    $('#use-national-average-premium').click(function() {
      $('#monthly-insurance-premium-input').val(185)
    })

    $('#use-national-90th-percentile-premium').click(function() {
      $('#monthly-insurance-premium-input').val(675)
    })

    $('#use-national-average-oop').click(function() {
      $('#annual-out-of-pocket-costs-input').val(800)
    })

    $('#use-national-90th-percentile-oop').click(function() {
      $('#annual-out-of-pocket-costs-input').val(5000)
    })

    $('#use-national-average-dental').click(function() {
      $('#annual-dental-costs-input').val(360)
    })

    $('#use-national-average-vision').click(function() {
      $('#annual-vision-costs-input').val(200)
    })

    $('#use-national-average-hearing').click(function() {
      $('#annual-hearing-costs-input').val(2700)
    })

    $('#use-national-average-drug').click(function() {
      $('#annual-drug-costs-input').val(1020)
    })

    // remove anything that's not a number
    $("input").on('blur', function(){
      $(this).val( $(this).val().replace(/\D/g, ''))
    })

    function updateButtonInformation() {
      var empty = false;
        $('input').each(function() {
            if ($(this).val() == '') {
                empty = true;
            }
        });

        if(!($("input").serializeArray().find( (x) => x.name === "calculation[filing_type]"))){
          empty = true;
        }

        if (empty) {
          $("#enabled-button").addClass("hidden")
          $("#disabled-button").removeClass("hidden")
        } else {
          $("#disabled-button").addClass("hidden")
          $("#enabled-button").removeClass("hidden")
        }
    }

    updateButtonInformation() // for pageload

    $(".trigger-check").click(function(){
      updateButtonInformation() // for pageload
    })

    $('input').on('keyup change', function() {
        updateButtonInformation() // for form updates
    });
  })

app/views/calculations/edit.html.slim
.row.justify-content-center.bg-soft-gray.mv-2
  .col-xs-12.col-sm-10.col-md-8.col-lg-7.col-xl-5.text-center
    h1 SANDERS MEDICARE FOR ALL COST CALCULATOR

.row.justify-content-center
  .col-xs-12.col-sm-10.col-md-8.col-lg-7.col-xl-6
    == render 'form'

app/views/calculations/index.html.slim
h1 Listing calculations

table
  thead
    tr
      th Annual income
      th Capital gains
      th Deduction
      th Dependent children
      th
      th
      th

  tbody
    - @calculations.each do |calculation|
      tr
        td = calculation.annual_income
        td = calculation.capital_gains
        td = calculation.deduction
        td = calculation.dependent_children
        td = link_to 'Show', calculation
        td = link_to 'Edit', edit_calculation_path(calculation)
        td = link_to 'Destroy', calculation, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Calculation', new_calculation_path

app/views/calculations/new.html.slim
.row.justify-content-center.bg-soft-gray.mv-2
  .col-xs-12.col-sm-10.col-md-8.col-lg-7.col-xl-5.text-center
    h1 SANDERS MEDICARE FOR ALL COST CALCULATOR

    p.lead Want to know what the <b>actual</b> difference in total costs will be for you be if the United States were to move from its current health insurance system to the #{link_to "Medicare for All plan proposed by Bernie Sanders", "https://berniesanders.com/issues/medicare-for-all/", target: "_blank"}?  Fill out just a few fields below, and we'll tell you exactly what the difference is!  It takes just a minute to fill out, and we don't collect <b>any</b> identifying information.

.row.justify-content-center
  .col-xs-12.col-sm-10.col-md-8.col-lg-7.col-xl-6
    == render 'form'

app/views/calculations/show.html.slim
.alert.alert-success.tiny-toast-alert#link-copied.hidden Link copied!

.row.justify-content-center.bg-soft-gray.mv-2
  .col-xs-12.col-sm-10.col-md-8.col-lg-7.col-xl-5.text-center
    h1 SANDERS MEDICARE FOR ALL COST CALCULATOR

.row.justify-content-center.mt-5
  .col-xs-12.col-sm-10.col-md-8.col-lg-7.col-xl-6
    p.lead Your results (based on total earnings of <b>#{number_to_currency(@calculation.annual_income + @calculation.capital_gains, precision: 0)}</b>):

.row.justify-content-center.mt-4
  .col-xs-12.col-sm-10.col-md-8.col-lg-7.col-xl-6
    .table-responsive.text-center
      table.table.table-bordered.table-hover
        thead.thead-dark
          tr
            th scope="col"
            th scope="col" Current
            th scope="col" Medicare for All
            th scope="col" Difference
        tbody
          tr
            th.bg-soft-gray scope='row' Taxes
            td = number_to_currency(@old_total_taxes, precision: 0)
            td = number_to_currency(@new_total_taxes, precision: 0)
            td = number_to_currency(@tax_difference, precision: 0)
          tr
            th.bg-soft-gray scope='row' Medical costs
            td = number_to_currency(@old_expenses, precision: 0)
            td = number_to_currency(@new_expenses, precision: 0)
            td = number_to_currency(@expenses_difference, precision: 0)
          tr
            th.bg-soft-gray scope='row' Total
            td = number_to_currency(@old_total, precision: 0)
            td = number_to_currency(@new_total, precision: 0)
            td.table-success
              b = number_to_currency(@total_difference, precision: 0)

.row.justify-content-center.mt-3
  .col-xs-12.col-sm-10.col-md-8.col-lg-7.col-xl-6
    - if @total_difference > 0
      p.lead Under the Sanders Medicare for All plan, you would <b>save #{number_to_currency(@total_difference, precision: 0)}</b> per year!
    - elsif @total_difference == 0
      p.lead Under the Sanders Medicare for All plan, your total health care costs (considering both out of pocket spending and taxes) <b>would not change</b>.
    - else
      p.lead Under the Sanders Medicare for All plan, you would pay an additional #{number_to_currency(-1 * @total_difference, precision: 0)} per year with your current health care costs.

    hr

    p.lead Want to share these results with others?  <span class="link-like" id="copy-link">Click here to get a shareable link!</span>
    - if params[:token] == @calculation.edit_token
      p.lead Curious what would happen if something changed? #{link_to "Click here to edit your inputs", edit_calculation_path(@calculation, token: @calculation.edit_token)}.

javascript:
  document.addEventListener("turbolinks:load", function() {
    $('#copy-link').click(function(){
      var $temp = $("<input>");
      $("body").append($temp);
      var path = "#{ request.base_url + calculation_path(@calculation) }"
      $temp.val( path ).select();
      document.execCommand("copy");
      $temp.remove();

      $("#link-copied").removeClass("hidden")
      setTimeout(function() {
        $("#link-copied").fadeOut(1500, function(){
          $("#link-copied").addClass("hidden")
          $("#link-copied").css("display", "")
        })
      }, 1500)
    })
  })

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"

    title
      | Sanders M4A Calculator

    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    header
      nav.navbar.navbar-expand-md.navbar-dark.fixed-top.bg-dark
        a.navbar-brand[href="#"]
          | M4A Calculator
        button.navbar-toggler[type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation"]
          span.navbar-toggler-icon
        #navbarCollapse.collapse.navbar-collapse
          ul.navbar-nav.ml-auto
            li.nav-item.active
              a.nav-link[href="#"]
                | About
            / li.nav-item
            /   a.nav-link[href="#"]
            /     | Link
            / li.nav-item
            /   a.nav-link.disabled[href="#"]
            /     | Disabled
    main.container-fluid[role="main"]
      - if alert
        .row.alert-row
          .col-12.text-center.mt-3
            p.lead = alert
      = yield
      / h1.mt-5
      /   | Sticky footer with fixed navbar
      / p.lead
      /   | Pin a fixed-height footer to the bottom of the viewport in desktop browsers with this custom HTML and CSS. A fixed navbar has been added with 
      /   code
      /     | padding-top: 60px;
      /   |  on the 
      /   code
      /     | body > .container
      /   | .
      / p
      /   | Back to 
      /   a[href="../sticky-footer/"]
      /     | the default sticky footer
      /   |  minus the navbar.
    footer.footer
      .container
        span.text-muted
          | This site is not officially related to <i>Bernie 2020</i> in any way.